source "https://rubygems.org"

gem "webrick", "~> 1.7"
gem "jekyll", "~> 4.2"


group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-mermaid"
  gem "jekyll-liquify"
  gem 'jekyll-pug'
  gem "jekyll-environment-variables"
end